version: '3.3'
services:
  api:
    build: ./
    restart: unless-stopped
    networks:
    - flask
    ports:
    - 8080:8080

  db:
    image: postgres
    volumes:
    - postgres:/var/lib/postgresql

volumes:
  postgres:
    external: true
networks:
  flask:
    external: true
